---
# role: ansible-role-ssh
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: ../requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ssh-alpine311
    image: "jam82/molecule-alpine:3.11"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: ssh-alpine
    image: "jam82/molecule-alpine:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: ssh-amazonlinux
    image: "jam82/molecule-amazonlinux:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-arch
    image: "jam82/molecule-archlinux:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-centos7
    image: "jam82/molecule-centos:7"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-centos8
    image: "jam82/molecule-centos:8"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-debian9
    image: "jam82/molecule-debian:9"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-debian10
    image: "jam82/molecule-debian:10"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-fedora
    image: "jam82/molecule-fedora:32"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-opensuse15
    image: "jam82/molecule-opensuse:15"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-opensuse-tumbleweed
    image: "jam82/molecule-opensuse:tumbleweed"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-oraclelinux7
    image: "jam82/molecule-oraclelinux:7"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-oraclelinux8
    image: "jam82/molecule-oraclelinux:8"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-oraclelinux
    image: "jam82/molecule-oraclelinux:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-ubuntu1604
    image: "jam82/molecule-ubuntu:16.04"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-ubuntu1804
    image: "jam82/molecule-ubuntu:18.04"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-ubuntu2004
    image: "jam82/molecule-ubuntu:20.04"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  inventory:
    group_vars:
      all:
        ssh_role_enabled: True
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: True
    sudo: True
