---
# role: ansible-role-ssh
# file: tasks/hostkeys.yml

# This is a bit ugly for several reasons:
# 1. Debian-Family distros start sshd after installation and
# generate rsa host keys with 2048 bits.
# 2. openssh_keypair module is not idempotent, the return value 'size' is
# the desired, not the current key size, so you cannot replace when
# different size as desired...

- name: Check for {{ hostkey.type }} capability
  shell: "set -o pipefail && ssh -Q key | grep {{ hostkey.type }} | wc -l"
  args:
    executable: /bin/bash
  changed_when: false
  register: ssh_hostkey_capability
  check_mode: false

- name: Check if host {{ hostkey.path }} exists
  stat:
    path: "{{ hostkey.path }}"
  register: hostkey_file

- name: Create {{ hostkey.path }} if it does not exist
  shell: |
    set -o pipefail && echo -e 'y' | \
    ssh-keygen -q \
    -t {{ hostkey.type }} \
    -b {{ hostkey.size | default(4096) }} \
    -f {{ hostkey.path }} >/dev/null \
    -C {{ ansible_fqdn | default(ansible_nodename, true) }} \
    -N ''
  args:
    executable: /bin/bash
  check_mode: false
  when: ssh_hostkey_capability.stdout | default(0, true) | int > 0
    and (not hostkey_file.stat.exists) | bool

- name: Check {{ hostkey.path }} size
  shell: |
    set -o pipefail && ssh-keygen -l -f {{ hostkey.path }} | awk '{ print $1 }'
  args:
    executable: /bin/bash
  changed_when: false
  register: ssh_hostkey_size
  check_mode: false
  when: ssh_hostkey_capability.stdout | default(0, true) | int > 0

- name: Recreate {{ hostkey.path }} if it has a wrong size or forced
  shell: |
    set -o pipefail && echo -e 'y' | \
    ssh-keygen -q \
    -t {{ hostkey.type }} \
    -b {{ hostkey.size | default(4096) }} \
    -f {{ hostkey.path }} >/dev/null \
    -C {{ ansible_fqdn | default(ansible_nodename, true) }} \
    -N ''
  args:
    executable: /bin/bash
  check_mode: false
  when: ssh_hostkey_capability.stdout | default(0, true) | int > 0
    and (ssh_hostkey_size.stdout | int |
    default(0, true) != (hostkey.size | default(4096, true))
    or sshd_host_keys_regenerate | bool)

- name: Set permissions for private hostkeys
  file:
    path: "{{ hostkey.path }}"
    owner: root
    group: root
    mode: '0600'
  when: ssh_hostkey_capability.stdout | default(0, true) | int > 0

- name: Set permissions for public hostkeys
  file:
    path: "{{ hostkey.path }}.pub"
    owner: root
    group: root
    mode: '0644'
  when: ssh_hostkey_capability.stdout | default(0, true) | int > 0
