---
# role: ansible-role-ssh
# file: tasks/setup.yml

# binutils are needed below ssh 6.3, because -Q option is not available.
# - name: Install binutils for algorithm extraction
#   package:
#     name: "{{ ssh_tools_packages }}"
#     state: present

- name: Install ssh client packages
  package:
    name: "{{ ssh_packages }}"
    state: present
  when: ssh_enabled | bool
    or sshd_enabled | bool

- name: Install ssh server packages
  package:
    name: "{{ sshd_packages }}"
    state: present
  when: sshd_enabled | bool

- name: Check if {{ sshd_moduli_file }} contains weak DH parameters
  shell: awk '$5 < {{ sshd_moduli_minimum }}' {{ sshd_moduli_file }}
  register: sshd_register_moduli
  changed_when: false
  check_mode: no

- name: Remove primes smaller than {{ sshd_moduli_minimum }}
  shell: |
    awk '$5 >= {{ sshd_moduli_minimum }}' {{ sshd_moduli_file }} > \
    {{ sshd_moduli_file }}.new
    [ -f {{ sshd_moduli_file }}.new ] && \
    mv {{ sshd_moduli_file }}.new {{ sshd_moduli_file }} || true
  when: sshd_register_moduli.stdout
