---
# role: ansible-role-ssh
# file: tasks/ssh.yml

- name: Set up default configuration of ssh in /etc/ssh/ssh_config
  template:
    src: 'etc/ssh/ssh_config.j2'
    dest: '/etc/ssh/ssh_config'
    mode: '0644'
    owner: 'root'
    group: 'root'
    backup: "{{ ssh_conf_backup }}"

- name: Create ~/.ssh directory and set permissions
  file:
    path: ~/.ssh/
    state: directory
    mode: '0700'
    modification_time: preserve
    access_time: preserve

- name: "TESTING"
  block:
    - name: "TESTING --- Create user"
      user:
        name: test
        password: $6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1

    - name: "TESTING --- Create ssh key"
      openssh_keypair:
        path: '~/.ssh/identity'

    - name: "TESTING --- Get public key"
      command: cat ~/.ssh/identity.pub
      register: pubkey
      changed_when: false

    - name: "TESTING --- Setup authorized_key file"
      authorized_key:
        user: test
        state: present
        key: "{{ pubkey.stdout }}"
  when: ssh_test_create_key | bool
