---
# role: ansible-role-ssh
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ssh-alpine310
    box: "generic/alpine310"
    cpus: 2
    memory: 1024
  - name: ssh-arch
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: ssh-centos8
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: ssh-debian10
    box: "debian/buster64"
    cpus: 2
    memory: 1024
  - name: ssh-fedora32
    box: "fedora/32-cloud-base"
    cpus: 2
    memory: 1024
  - name: ssh-ubuntu1804
    box: "ubuntu/bionic64"
    cpus: 2
    memory: 1024
  - name: ssh-ubuntu2004
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  inventory:
    group_vars:
      all:
        ssh_role_enabled: true
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: true
    sudo: true
