---
# role: ansible-role-ssh
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 2048
      cpus: 2
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ssh-arch
    box: "archlinux/archlinux"
  - name: ssh-centos8
    box: "centos/8"
  - name: ssh-debian10
    box: "debian/buster64"
  - name: ssh-fedora32
    box: "fedora/32-cloud-base"
  - name: ssh-ubuntu2004
    box: "generic/ubuntu2004"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  inventory:
    group_vars:
      all:
        ssh_role_enabled: true
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: true
    sudo: true
